### ISSUE TITLE
(32-bits) pacman does not use the proper architecture on all 32-bit devices

### ISSUE THREAD

**Issue by Yisus7u7** [Maxython/pacman-for-termux#12]
![Screenshot_20210831-093130](https://user-images.githubusercontent.com/64093255/131522513-017834af-5ead-43be-b4d7-733a7ac1ea95.png)
![Screenshot_20210831-093327](https://user-images.githubusercontent.com/64093255/131522524-554a1091-3355-4718-bf49-964c38e0cb93.png)

Pacman does not define a single architecture for 32-bit devices, the architecture results in : armv7l, armv7h and armv7a

Unlike dpkg in termux, all 32-bit cell phones use the same architecture (arm).

**Comment by Maxython** [comment]
You need to change the `Architecture` value in the `pacman.conf` file, it is set to `auto`.  In your case, you need to change to `armv7`.   

The installation script does not have an architecture configuration step for the pacman termux type.

**Comment by Yisus7u7** [comment]
> You need to change the `Architecture` value in the `pacman.conf` file, it is set to `auto`. In your case, you need to change to `armv7`.
> 
> The installation script does not have an architecture configuration step for the pacman termux type.

The architecture provided by your PKGBUILD is not armv7, it is armv7a

**Comment by Maxython** [comment]
Reinstall pacman and compile again.  
I added this stage.
