### ISSUE TITLE
Pacman key

### ISSUE THREAD

**Issue by Dendi777** [Maxython/pacman-for-termux#17]
Help me!
![Screenshot_2022-10-31-19-41-04-205_com termux](https://user-images.githubusercontent.com/97088046/199066913-7404d554-3665-4cb8-baf3-5a050fa3a3b6.jpg)
![Screenshot_2022-10-31-19-41-08-392_com termux](https://user-images.githubusercontent.com/97088046/199066917-e60c93e5-3fd3-47cc-98f0-01e62b25475f.jpg)

**Comment by Maxython** [comment]
Run it
```
pacman-key --init
pacman-key --populate
```

**Comment by Dendi777** [comment]
==> ERROR: No keyring files exist in /data/data/com.termux/files/usr/share/pacman/keyrings.

**Comment by Dendi777** [comment]
And when he tries to update, he tries to port the keys, but he can't
error: main: key "998DE27318E867EA976BA877389CEED64573DFCA" is unknown

**Comment by Dendi777** [comment]
![Screenshot_2022-11-01-13-12-55-302_com termux](https://user-images.githubusercontent.com/97088046/199211133-634b8905-fcf3-45a5-bcac-21bcb4eca577.jpg)

**Comment by Imshubh69** [comment]
> Then take the following steps:
> 
> 1. Open the `pacman.conf` file (`nano $PREFIX/etc/pacman.conf`).
> 2. Find the `SigLevel` value and change the value to `Never` (`SigLevel = Never`).
> 3. Save and close the file and install the `termux-keyring` package (`pacman -Syy termux-keyring`).
> 4. After that, open this file again and change the value of SigLevel to what it was before (`SigLevel = DatabaseRequired`).
> 
> After these steps, pacman should work.

still not working 🐧

**Comment by Dendi777** [comment]
![Screenshot_2022-11-01-13-46-15-318_com termux](https://user-images.githubusercontent.com/97088046/199216670-292080ed-708f-494b-b96d-a3fdf98ceec2.jpg)

**Comment by Dendi777** [comment]
As far as I understand, I am not the only one who has encountered this problem

**Comment by Dendi777** [comment]
It looks like you have removed or damaged the config files, I noticed that some files that were previously present are now gone

**Comment by Imshubh69** [comment]
![Screenshot_20221101-162313_Termux](https://user-images.githubusercontent.com/101496164/199217606-7007d894-111c-48f4-bfe2-4137d40c574b.png)
seems like my problem is different from this guy's problem but you still made by issue duplicate

**Comment by Dendi777** [comment]
So I just noticed that if you leave the SigLevel config Never, then everything works, but if you change it back, it asks for keys again

**Comment by Dendi777** [comment]
Will there be problems if SigLevel is left Never?

**Comment by Imshubh69** [comment]
> ![Screenshot_20221101-162313_Termux](https://user-images.githubusercontent.com/101496164/199217606-7007d894-111c-48f4-bfe2-4137d40c574b.png) seems like my problem is different from this guy's problem but you still made by issue duplicate

@Maxython isn't there any solution to my problem?

**Comment by Imshubh69** [comment]
> ![Screenshot_20221101-162313_Termux](https://user-images.githubusercontent.com/101496164/199217606-7007d894-111c-48f4-bfe2-4137d40c574b.png) seems like my problem is different from this guy's problem but you still made by issue duplicate

@Maxython isn't there any solution to my problem?

**Comment by Dendi777** [comment]
It looks like pacman is currently in serious trouble

**Comment by Imshubh69** [comment]
![Screenshot_20221101-164245_Brave](https://user-images.githubusercontent.com/101496164/199220847-9dedb73b-c0b3-4940-a70c-b8f6f6ab3e53.png)
seems like these buckets do not exist
![Screenshot_20221101-164243_Termux](https://user-images.githubusercontent.com/101496164/199220865-df03885d-e6b7-491a-9709-33a1e0c60df8.png)

**Comment by Imshubh69** [comment]
> It looks like pacman is currently in serious trouble

can you 
`nano $PREFIX/etc/pacman.conf` and send your server URLs 🐧

**Comment by Imshubh69** [comment]
> Everyone has the same server!

but why mine https://s3.amazonaws.com/termux-main.pac not working

**Comment by Dendi777** [comment]
I suggest using a workaround for a while: Remove pacman and install it again but not update it (apt autoremove --purge pacman) , replace SigLevel = DatabaseRequired with SigLevel = Never, and use it!

**Comment by Dendi777** [comment]
Try it https://s3.amazonaws.com/termux-pacman.us/main /$arch

**Comment by Dendi777** [comment]
And it also seems to me that there is something with the pacman-keyrings package or with its installation

**Comment by Imshubh69** [comment]
@Dendi777 we are now in the same tree
have some problem as yours now 🐧

**Comment by Maxython** [comment]
Before proceeding, I would like to get the result of `termux-info`.

**Comment by Dendi777** [comment]
![Uploading Screenshot_2022-11-01-14-32-31-991_com.termux.jpg…]()

**Comment by Dendi777** [comment]
![Screenshot_2022-11-01-14-32-31-991_com termux](https://user-images.githubusercontent.com/97088046/199223968-305a377f-2f88-4a0d-ace3-1d69b6cccb87.jpg)

**Comment by Dendi777** [comment]
So it seems that even the workaround does not work when installing something, just a huge output with an error at the end of the output until the problem with the keys is solved, nothing will work

**Comment by Maxython** [comment]
And so, I noticed that @Imshubh69 compiled pacman from this repository. Which I highly do not recommend, since this pacman has an old code (better install via apt). I also want to note that you have not configured pacman as the default package manager, which means that you cannot use pacman fully. If you want to use pacman as an add-on to your termux, then you just need to change the value of SigLevel. But if you want to use pacman fully, then you will need to follow the steps listed [here](https://wiki.termux.com/wiki/Switching_package_manager) (note: doing this you will have to change the SigLevel value).

**Comment by Dendi777** [comment]
Unfortunately, none of the 2 methods helped, the error lies in something else (and my assumption is that there is still something with the keys, since he does not even want to install it, and when trying to install something, a huge log appears with errors at the end of each: exists in filesystem, the same as when trying to install pacman-keyring

**Comment by Maxython** [comment]
> Unfortunately, none of the 2 methods helped, the error lies in something else (and my assumption is that there is still something with the keys)

I understand you are trying to set up pacman as the default package manager. To make pacman work, you just need to change the value of `SigLevel` to `Never` in the `pacman.conf` file to disable the database check. After that, you can start configuring pacman.

> exists in filesystem, the same as when trying to install pacman-keyring

Did you mean `termux-keyring`?

**Comment by Dendi777** [comment]
So SigLevel I have is Never yes, I mean installing termux-keyring, I can record a video about everything that happens when using pacman if you don't mind

**Comment by Maxython** [comment]
> So SigLevel I have is Never yes, I mean installing termux-keyring, I can record a video about everything that happens when using pacman if you don't mind

This is because pacman is not your default package manager (it is apt by default). As mentioned above, to make pacman the default, you need to follow some steps (https://wiki.termux.com/wiki/Switching_package_manager). You can't use two default package managers in termux, as this can break the system.

**Comment by Dendi777** [comment]
So just somehow, but everything worked (Ps: I didn't do anything by myself) I don't understand how (considering that I didn't even put a pacman by default)

**Comment by Dendi777** [comment]
I think the question can be closed, but still I'm scared when reinstalling pacman whether it will break and whether it will work, I don't even know why it started working abruptly

**Comment by Maxython** [comment]
So I understand that you are new to using pacman. Tip: to understand what kind of pacman system, just google it well )

**Comment by Dendi777** [comment]
No I'm not new to pacman it's just that mistakes are misleading
