### ISSUE TITLE
Failed to synchronise pakage database 

### ISSUE THREAD

**Issue by Imshubh69** [Maxython/pacman-for-termux#18]
I installed this first time and when I run pacman -Sy or try to install any pakage it shows me this error
![Screenshot_20221101-155809_Termux](https://user-images.githubusercontent.com/101496164/199213806-87759b53-1343-4b27-9b21-a45174eba693.png)
Is there anything I can do?

DEVICE: ONEPLUS 7T
ANDROID VERSION: 12 (CUSTOM ROM)

**Comment by Maxython** [comment]
Repeat #17
