### ISSUE TITLE
I'm all in #meta

### ISSUE THREAD

**Issue by RupankarGhosh** [Maxython/pacman-for-termux#8]
This repo looks so promising that all I wanted from 2015 to run Pacman directly in termux. I'm all in for this ...

**Comment by RupankarGhosh** [comment]
Q1: will this break my android system in anyway...?

**Comment by Maxython** [comment]
All two kinds of pacman (arch and termux) will not break android system.  But with **pacman-arch**, there is a chance to break the termux system if no additional steps are taken.  You can try `makepkg` on **pacman-termux**, but this pacman cannot install the termux packages at this time.
